create table users
(
    id         bigint generated by default as identity,
    name       varchar(20),
    email      varchar(50),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table account
(
    id         bigint generated by default as identity,
    user_id    bigint      not null,
    type      varchar(10) not null,
    balance    bigint      not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table transaction
(
    id         bigint generated by default as identity,
    account_id    bigint      not null,
    transaction_type      varchar(10) not null,
    amount    bigint      not null,
    created_at timestamp(6),
    created_date timestamp(6),
    primary key (id)
);