spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:pay'
    username: user

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true